services:
  - type: web
    name: plc-copilot-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120 --workers 1"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: plc-copilot-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: OPENAI_VECTOR_STORE_ID
        sync: false
      - key: ENVIRONMENT
        value: "production"
      - key: DEBUG
        value: "false"
      - key: API_V1_STR
        value: "/api/v1"
      - key: PROJECT_NAME
        value: "PLC Copilot"
      - key: BACKEND_CORS_ORIGINS
        value: "https://jonaspetersen.com,https://www.jonaspetersen.com,http://localhost:3000,https://localhost:3000,http://localhost:3001,https://localhost:3001"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_FILE_TYPES
        value: "application/pdf,text/plain"
      - key: UPLOAD_DIR
        value: "/opt/render/project/src/uploads"

databases:
  - name: plc-copilot-db
    databaseName: plc_copilot
    user: plc_copilot_user
    plan: starter